SELECT
  "RegulatedEntity".*,
  "reInspectionType"."id" AS "reInspectionType.id",
  "reInspectionType"."clientCode" AS "reInspectionType.clientCode",
  "reInspectionType"."externalId" AS "reInspectionType.externalId",
  "reInspectionType"."regulatedEntityId" AS "reInspectionType.regulatedEntityId",
  "reInspectionType"."inspectionTypeCode" AS "reInspectionType.inspectionTypeCode",
  "reInspectionType"."name" AS "reInspectionType.name",
  "reInspectionType"."address" AS "reInspectionType.address",
  "reInspectionType"."latitude" AS "reInspectionType.latitude",
  "reInspectionType"."longitude" AS "reInspectionType.longitude",
  "reInspectionType"."state" AS "reInspectionType.state",
  "reInspectionType"."county" AS "reInspectionType.county",
  "reInspectionType"."municipality" AS "reInspectionType.municipality",
  "reInspectionType"."mailingAddress" AS "reInspectionType.mailingAddress",
  "reInspectionType"."attributeMap" AS "reInspectionType.attributeMap",
  "reInspectionType"."clientMetaData" AS "reInspectionType.clientMetaData",
  "reInspectionType"."zip" AS "reInspectionType.zip",
  "reInspectionType"."country" AS "reInspectionType.country",
  "reInspectionType"."active" AS "reInspectionType.active",
  "reInspectionType"."deleted" AS "reInspectionType.deleted",
  "reInspectionType"."createdBy" AS "reInspectionType.createdBy",
  "reInspectionType"."updatedBy" AS "reInspectionType.updatedBy",
  "reInspectionType"."createdAt" AS "reInspectionType.createdAt",
  "reInspectionType"."updatedAt" AS "reInspectionType.updatedAt",
  "reInspectionType"."regStartDate" AS "reInspectionType.regStartDate",
  "reInspectionType->reItem"."id" AS "reInspectionType.reItem.id",
  "reInspectionType->reItem"."clientCode" AS "reInspectionType.reItem.clientCode",
  "reInspectionType->reItem"."externalId" AS "reInspectionType.reItem.externalId",
  "reInspectionType->reItem"."regulatedEntityInspectionTypeId" AS "reInspectionType.reItem.regulatedEntityInspectionTypeId",
  "reInspectionType->reItem"."regulatedEntityId" AS "reInspectionType.reItem.regulatedEntityId",
  "reInspectionType->reItem"."keyName" AS "reInspectionType.reItem.keyName",
  "reInspectionType->reItem"."keyValue" AS "reInspectionType.reItem.keyValue",
  "reInspectionType->reItem"."attributeMap" AS "reInspectionType.reItem.attributeMap",
  "reInspectionType->reItem"."active" AS "reInspectionType.reItem.active",
  "reInspectionType->reItem"."deleted" AS "reInspectionType.reItem.deleted",
  "reInspectionType->reItem"."createdBy" AS "reInspectionType.reItem.createdBy",
  "reInspectionType->reItem"."updatedBy" AS "reInspectionType.reItem.updatedBy",
  "reInspectionType->reItem"."createdAt" AS "reInspectionType.reItem.createdAt",
  "reInspectionType->reItem"."updatedAt" AS "reInspectionType.reItem.updatedAt",
  "reInspectionType->reItem->attachments"."id" AS "reInspectionType.reItem.attachments.id",
  "reInspectionType->reItem->attachments"."regulatedEntityInspectionTypeId" AS "reInspectionType.reItem.attachments.regulatedEntityInspectionTypeId",
  "reInspectionType->reItem->attachments"."regulatedEntityItemId" AS "reInspectionType.reItem.attachments.regulatedEntityItemId",
  "reInspectionType->reItem->attachments"."mimeType" AS "reInspectionType.reItem.attachments.mimeType",
  "reInspectionType->reItem->attachments"."title" AS "reInspectionType.reItem.attachments.title",
  "reInspectionType->reItem->attachments"."description" AS "reInspectionType.reItem.attachments.description",
  "reInspectionType->reItem->attachments"."active" AS "reInspectionType.reItem.attachments.active",
  "reInspectionType->reItem->attachments"."deleted" AS "reInspectionType.reItem.attachments.deleted",
  "reInspectionType->reItem->attachments"."createdBy" AS "reInspectionType.reItem.attachments.createdBy",
  "reInspectionType->reItem->attachments"."updatedBy" AS "reInspectionType.reItem.attachments.updatedBy",
  "reInspectionType->reItem->attachments"."createdAt" AS "reInspectionType.reItem.attachments.createdAt",
  "reInspectionType->reItem->attachments"."updatedAt" AS "reInspectionType.reItem.attachments.updatedAt",
  "reInspectionType->reItem->attachments"."metaData" AS "reInspectionType.reItem.attachments.metaData",
  "reInspectionType->reItem->attachments"."annotations" AS "reInspectionType.reItem.attachments.annotations",
  "reInspectionType->reItem->attachments"."annotationTypes" AS "reInspectionType.reItem.attachments.annotationTypes",
  "reInspectionType->reItem->attachments"."contextType" AS "reInspectionType.reItem.attachments.contextType",
  "reInspectionType->reItem->attachments"."regulatedEntityId" AS "reInspectionType.reItem.attachments.regulatedEntityId",
  "reInspectionType->contacts"."id" AS "reInspectionType.contacts.id",
  "reInspectionType->contacts"."regulatedEntityInspectionTypeId" AS "reInspectionType.contacts.regulatedEntityInspectionTypeId",
  "reInspectionType->contacts"."contactType" AS "reInspectionType.contacts.contactType",
  "reInspectionType->contacts"."firstname" AS "reInspectionType.contacts.firstname",
  "reInspectionType->contacts"."middlename" AS "reInspectionType.contacts.middlename",
  "reInspectionType->contacts"."lastname" AS "reInspectionType.contacts.lastname",
  "reInspectionType->contacts"."address" AS "reInspectionType.contacts.address",
  "reInspectionType->contacts"."city" AS "reInspectionType.contacts.city",
  "reInspectionType->contacts"."state" AS "reInspectionType.contacts.state",
  "reInspectionType->contacts"."zip" AS "reInspectionType.contacts.zip",
  "reInspectionType->contacts"."default" AS "reInspectionType.contacts.default",
  "reInspectionType->contacts"."active" AS "reInspectionType.contacts.active",
  "reInspectionType->contacts"."deleted" AS "reInspectionType.contacts.deleted",
  "reInspectionType->contacts"."createdBy" AS "reInspectionType.contacts.createdBy",
  "reInspectionType->contacts"."updatedBy" AS "reInspectionType.contacts.updatedBy",
  "reInspectionType->contacts"."createdAt" AS "reInspectionType.contacts.createdAt",
  "reInspectionType->contacts"."updatedAt" AS "reInspectionType.contacts.updatedAt",
  "reInspectionType->contacts"."workPhone" AS "reInspectionType.contacts.workPhone",
  "reInspectionType->contacts"."workEmail" AS "reInspectionType.contacts.workEmail",
  "reInspectionType->contacts"."clientMetaData" AS "reInspectionType.contacts.clientMetaData",
  "reInspectionType->contacts"."title" AS "reInspectionType.contacts.title",
  "reInspectionType->contacts"."regulatedEntityId" AS "reInspectionType.contacts.regulatedEntityId",
  "reInspectionType->attachments"."id" AS "reInspectionType.attachments.id",
  "reInspectionType->attachments"."regulatedEntityInspectionTypeId" AS "reInspectionType.attachments.regulatedEntityInspectionTypeId",
  "reInspectionType->attachments"."regulatedEntityItemId" AS "reInspectionType.attachments.regulatedEntityItemId",
  "reInspectionType->attachments"."mimeType" AS "reInspectionType.attachments.mimeType",
  "reInspectionType->attachments"."title" AS "reInspectionType.attachments.title",
  "reInspectionType->attachments"."description" AS "reInspectionType.attachments.description",
  "reInspectionType->attachments"."active" AS "reInspectionType.attachments.active",
  "reInspectionType->attachments"."deleted" AS "reInspectionType.attachments.deleted",
  "reInspectionType->attachments"."createdBy" AS "reInspectionType.attachments.createdBy",
  "reInspectionType->attachments"."updatedBy" AS "reInspectionType.attachments.updatedBy",
  "reInspectionType->attachments"."createdAt" AS "reInspectionType.attachments.createdAt",
  "reInspectionType->attachments"."updatedAt" AS "reInspectionType.attachments.updatedAt",
  "reInspectionType->attachments"."metaData" AS "reInspectionType.attachments.metaData",
  "reInspectionType->attachments"."annotations" AS "reInspectionType.attachments.annotations",
  "reInspectionType->attachments"."annotationTypes" AS "reInspectionType.attachments.annotationTypes",
  "reInspectionType->attachments"."contextType" AS "reInspectionType.attachments.contextType",
  "reInspectionType->attachments"."regulatedEntityId" AS "reInspectionType.attachments.regulatedEntityId"
FROM
  (
    SELECT
      "RegulatedEntity"."id",
      "RegulatedEntity"."clientCode",
      "RegulatedEntity"."entityType",
      "RegulatedEntity"."externalId",
      "RegulatedEntity"."name",
      "RegulatedEntity"."address",
      "RegulatedEntity"."zip",
      "RegulatedEntity"."country",
      "RegulatedEntity"."state",
      "RegulatedEntity"."county",
      "RegulatedEntity"."municipality",
      "RegulatedEntity"."latitude",
      "RegulatedEntity"."longitude",
      "RegulatedEntity"."clientMetaData",
      "RegulatedEntity"."owners",
      "RegulatedEntity"."attributeMap",
      "RegulatedEntity"."active",
      "RegulatedEntity"."deleted",
      "RegulatedEntity"."createdBy",
      "RegulatedEntity"."updatedBy",
      "RegulatedEntity"."createdAt",
      "RegulatedEntity"."updatedAt"
    FROM
      "regulatedentityservice"."regulatedEntity" AS "RegulatedEntity"
    WHERE
      "RegulatedEntity"."clientCode" = 'CLIENT-071'
      AND "RegulatedEntity"."deleted" = false
    LIMIT
      1
  ) AS "RegulatedEntity"
  LEFT OUTER JOIN "regulatedentityservice"."regulatedEntityInspectionType" AS "reInspectionType" ON "RegulatedEntity"."id" = "reInspectionType"."regulatedEntityId"
  AND "reInspectionType"."deleted" = false
  LEFT OUTER JOIN "regulatedentityservice"."regulatedEntityItem" AS "reInspectionType->reItem" ON "reInspectionType"."id" = "reInspectionType->reItem"."regulatedEntityInspectionTypeId"
  AND "reInspectionType->reItem"."deleted" = false
  LEFT OUTER JOIN "regulatedentityservice"."attachments" AS "reInspectionType->reItem->attachments" ON "reInspectionType->reItem"."id" = "reInspectionType->reItem->attachments"."regulatedEntityItemId"
  AND "reInspectionType->reItem->attachments"."deleted" = false
  LEFT OUTER JOIN "regulatedentityservice"."contacts" AS "reInspectionType->contacts" ON "reInspectionType"."id" = "reInspectionType->contacts"."regulatedEntityInspectionTypeId"
  AND "reInspectionType->contacts"."deleted" = false
  LEFT OUTER JOIN "regulatedentityservice"."attachments" AS "reInspectionType->attachments" ON "reInspectionType"."id" = "reInspectionType->attachments"."regulatedEntityInspectionTypeId"
  AND "reInspectionType->attachments"."deleted" = false
  AND "reInspectionType->attachments"."regulatedEntityItemId" IS NULL;